### PR TITLE
Immaterial blank-space fixes to source for compiling with gfortran v6…

### PR DESCRIPTION
**Pull request by joshphacker**
….3.0 on Mac OSX, slight generalization of makefile, fixed one dependency in makefile.

Minor fixes to source files to include extra space after 'stop' command to result in successful build on Mac OSX with gfortran/gcc v6.3.0. Generalized makefile to remove hard-coded paths to /usr/local. Now requires environment variables NETCDF and FFTW. Added dependency time.o to mp_driver list.

### CODE REVIEW

**Comment by gutmann** [comment]
Thanks, I've focused mostly on earlier compilers and assumed newer compilers would just come along for the ride. I'll test this out with a suite of compilers and accept, thanks.

**Comment by kbnd** [comment]
@gutmann Adding time.o to the mp_driver list results in a failed compile. 

To fix this, in line 322 of the current makefile, move `$(BUILD)time.o \` to the top of the OBJS list.

**Comment by gutmann** [comment]
sorry, I merged this before I saw your comment.  I'll add an explicit dependency check there.  Right now I just want to get the travis builds working again

**Comment by gutmann** [comment]
@kbnd I'm not seeing this.  Can you post the error you are getting with the latest version?  The compile runs fine for me with multiple compilers on multiple computers, both with parallel and serial compiles.  You can see the latest compile run through Travis here: https://travis-ci.org/NCAR/icar

**Comment by joshphacker** [comment]
I've never seen this error before either, and can't figure out why it even exists:

/include -J build/ physics/lsm_driver.f90 -o build/lsm_driver.o
physics/lsm_driver.f90:394:16:

             stop("Simple LSM not settup, choose a different LSM options")
                1
Error: Blank required in STOP statement near (1)
make: *** [build/lsm_driver.o] Error 1

If I add a space after 'stop' it's no problem.

**Comment by gutmann** [comment]
Yes, I've seen the "STOP" error before.  I suspect it is one of those things that had always technically been incorrect, but no compiler had a problem with it until recently.  gfortran used to be fine with it (v4.x) but as of v5 or v6 it started treating this as an error.  But I'm not seeing the error @kbnd referred to regarding adding time.o to the dependency list.

**Comment by kbnd** [comment]
@gutmann I'm no longer receiving the time.o error. The last merge fixed the issue.

**Pull request merged**
